/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResponsiveGridImport } from './routes/responsive-grid'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ResponsiveGridRoute = ResponsiveGridImport.update({
  id: '/responsive-grid',
  path: '/responsive-grid',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/responsive-grid': {
      id: '/responsive-grid'
      path: '/responsive-grid'
      fullPath: '/responsive-grid'
      preLoaderRoute: typeof ResponsiveGridImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/responsive-grid': typeof ResponsiveGridRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/responsive-grid': typeof ResponsiveGridRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/responsive-grid': typeof ResponsiveGridRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/responsive-grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/responsive-grid'
  id: '__root__' | '/' | '/responsive-grid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResponsiveGridRoute: typeof ResponsiveGridRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResponsiveGridRoute: ResponsiveGridRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/responsive-grid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/responsive-grid": {
      "filePath": "responsive-grid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
